name: CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.zig'
      - '**.c'
      - '**.h'
  push:
    branches:
      - master
    paths:
      - '**.zig'
      - '**.c'
      - '**.h'

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.9.1
      - run: |
          DB_PATH=/tmp/test.db make test
          rm /tmp/test.db
