name: CI

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.org'
      - '.dir-locals.el'
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '**.md'
      - '**.org'
      - '.dir-locals.el'

env:
  GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
  DB_PATH: /tmp/test.db
  CC: gcc

jobs:
  test:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        zig-version: [0.12.0]
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ matrix.zig-version }}
      - run: make install-deps
      - name: gcc compile
        run: make all
      - name: zig compile
        run: |
          make clean
          zig build -Dquick=true -Dcpu=baseline --verbose
      - name: Test core
        if: matrix.os == 'ubuntu-latest'
        run: |
          TEST_BINARY=./zig-out/bin/test-core
          valgrind --leak-check=full --tool=memcheck \
          --show-leak-kinds=all --error-exitcode=1 ${TEST_BINARY}

      - name: Test discussion
        if: matrix.os == 'ubuntu-latest'
        run: |
          TEST_BINARY=./zig-out/bin/test-discussion
          valgrind --leak-check=full --tool=memcheck \
          --show-leak-kinds=all --error-exitcode=1 ${TEST_BINARY}
